### ISSUE TITLE
Doesn't support validation in multiple regions (Colliding TXT records)

### ISSUE THREAD

**Issue by joeykilpatrick** [mooyoul/aws-cdk-ses-domain-identity#30]
I am validating the same domain (`my.domain.com`) in multiple regions. However, each region tries to create a TXT record for `_amazonses.my.domain.com`. The first stack completes successfully, then the second stack (in another region) fails with the following message:
```
Received response status [FAILED] from custom resource. Message returned: [Tried to create resource record set [name='_amazonses.my.domain.com.', type='TXT'] but it already exists]
```

AWS docs say to create a multi-value TXT record ([here](https://aws.amazon.com/premiumsupport/knowledge-center/ses-verify-domain-accounts-regions/)).

I would be happy to submit a PR to handle the situation when a TXT record already exists, adding another value to the record. Let me know if this would be alright.

**Comment by mooyoul** [comment]
Hello @joeykilpatrick, Thanks for your reporting!

Oh yes, you're right. I never thought about multi-region deployment scenarios and it should be solved through your workaround. Happy to receive your PR if available!

**Comment by joeykilpatrick** [comment]
Thanks for the quick response, @mooyoul. I've submitted a PR. Let me know what you think.
