### ISSUE TITLE
Upgrade to CDK v2

### ISSUE THREAD

**Issue by abonstu** [mooyoul/aws-cdk-ses-domain-identity#36]
CDK v2 is the current stable version and requires some minor changes (making use of the new 'constructs' package in particular).

https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html

**Comment by mooyoul** [comment]
Hello there, Thanks for the information!
I'm interested in CDK v2 and it seems several people (you and @ChrisSargent) have done that migration task in your fork - It will be appreciated if you can open a PR. then I'll happily review your changes and will merge into master.
